import { editorialArticles } from './guide-editorial.mjs';

export const business = {
  name: 'Ellis Services Group',
  legalName: 'ELLIS SERVICES GROUP PTY LTD',
  abn: '96 645 821 745',
  acn: '645 821 745',
  entityType: 'Australian private company',
  abnStatus: 'Active since 11 November 2020',
  gstStatus: 'Registered since 11 November 2020',
  phone: '0405 878 406',
  phoneHref: 'tel:+61405878406',
  email: 'brian@elliservices.com.au',
  address: '121 Marcus Clarke St, Canberra, ACT 2600',
  map: 'https://maps.app.goo.gl/cvWgzfMPhPrDPZnE7',
  register: 'https://abr.business.gov.au/ABN/View?id=645821745',
  googleReviews: 'https://share.google/9J93sm3qIx44KCDtj',
  actRegister: 'https://www.accesscanberra.act.gov.au/business-and-work/public-registers',
};

export const services = [
  { slug: 'small-carpentry-jobs', title: 'Small Carpentry Jobs', group: 'General carpentry', intro: "Ellis Services Group repairs smaller timber items in Canberra and assesses several tasks together for a clear, itemised scope and quote.", symptoms: ['Loose or damaged timber fittings', 'A list of small repairs before a sale or tenancy change', 'Interior and exterior timber items that need attention'], approach: "Contact Ellis with your Canberra suburb and a short list of the tasks. Photos and measurements are optional: email safe photos to brian@elliservices.com.au if you have them. We assess each item on site and confirm the grouped repair scope, access and quote.", boundary: "We confirm the work included, visit arrangements and any minimum charge before booking. Our assessment identifies supporting timber damage and any qualified plumbing, electrical, glazing or structural work associated with the repair. The quote states hardware, painting and disposal inclusions; additional work is assessed and agreed with you before it proceeds.", related: ['door-and-frame-repairs','skirting-and-architraves','cabinet-door-and-drawer-repairs'] },
  { slug: 'door-and-frame-repairs', title: 'Timber Door & Frame Repairs', group: 'Doors and windows', intro: 'For timber doors that stick, scrape, will not latch, or have damaged frames, jambs and thresholds.', symptoms: ['A door rubbing after new flooring', 'A latch that misses the strike plate', 'Split timber around a hinge or a soft door jamb'], approach: "Tell Ellis which door sticks, scrapes or will not latch and your Canberra suburb. Optional safe photos can be emailed to brian@elliservices.com.au. We check the door, frame, hinges and latch on site and confirm the repair and quote.", boundary: "We check the full opening before confirming adjustment or repair. Our team confirms qualified hardware, glazing and compliance checks for lock mechanisms, powered access and fire-rated assemblies where relevant. Movement in the surrounding supports is assessed as part of defining the cause-based repair; the agreed scope identifies timber, hardware, finishing and access.", related: ['rotten-timber-repairs','skirting-and-architraves','timber-window-repairs'] },
  { slug: 'timber-window-repairs', title: 'Timber Window Repairs', group: 'Doors and windows', intro: 'Repairs to timber window frames, sills and weathered sections, with attention to the existing profile.', symptoms: ['Soft or damaged timber at a sill', 'Weathered frame sections', 'A frame that needs assessment before replacement'], approach: "Contact Ellis about the affected window and your Canberra suburb. Optional photos of the window and sill can be emailed to brian@elliservices.com.au. We inspect the timber, profile, glazing and water path and confirm the retained sections, repair and finish in your quote.", boundary: "We assess timber, glazing retention and water entry together. Required glazing, sash hardware and qualified building checks are coordinated in the work plan before timber is replaced and finished. We agree access to concealed joints where needed, record further findings and confirm additional work with you rather than treating a photograph as proof of sound concealed timber.", related: ['rotten-timber-repairs','fascia-and-eaves-repairs','door-and-frame-repairs'] },
  { slug: 'rotten-timber-repairs', title: 'Rotten Timber Repairs', group: 'Timber repair', intro: 'On-site inspection and repairs for damaged timber, including identifying the moisture source and the sections requiring replacement.', symptoms: ['Soft timber at an exterior opening', 'Repeated water damage', 'A damaged section requiring on-site inspection'], approach: "Contact Ellis with the timber location, damage you have noticed and your Canberra suburb. Reports and safe photos are optional and can be emailed to brian@elliservices.com.au. We assess the moisture source and sound retained timber before confirming your repair plan and quote.", boundary: "We identify the cause and confirm the repair plan and quote after on-site assessment. Our team arranges qualified leak, pest and structural checks required for the affected component. Agreed inspection access establishes the damage boundary at sound timber; additional concealed findings are documented and any change to the approved work and price is confirmed with you.", related: ['timber-window-repairs','door-and-frame-repairs','fascia-and-eaves-repairs'] },
  { slug: 'fascia-and-eaves-repairs', title: 'Fascia & Eaves Repairs', group: 'Exterior carpentry', intro: "Ellis Services Group assesses and repairs timber fascia boards, bargeboards and eaves details in Canberra, identifying materials and water sources before confirming the repair and quote.", metaDescription: 'Fascia and eaves repairs in Canberra for soft timber, split bargeboards and damaged lining. Identify the material and water source before work is scoped.', symptoms: ['Soft or peeling timber fascia near a gutter', 'A split or weathered bargeboard at a gable', 'A damaged eaves lining or soffit edge that needs material checks'], approach: "Contact Ellis about the affected fascia, bargeboard or eaves and your suburb. Optional photos taken safely from ground level can be emailed to brian@elliservices.com.au. We identify the material, inspect the water path and confirm safe access, repair arrangements and quote.", boundary: "Our team checks the moisture source and confirms the roofing or guttering trade arrangements required for the timber repair. We identify unknown lining materials and arrange qualified hazardous-material or electrical checks before disturbance. The quote sets out roof-edge access equipment, retained fixings, timber and finishing work, with any further concealed damage recorded and agreed before extra work.", related: ['rotten-timber-repairs','timber-weatherboard-repairs','timber-window-repairs'] },
  { slug: 'deck-repairs', title: 'Deck Repairs & Board Replacement', group: 'Outdoor timber', intro: 'Repair and board replacement for existing timber decks, with boards and framing considered separately.', symptoms: ['Individual deck boards that have deteriorated', 'Loose fixings or uneven boards', 'An older deck needing a repair-versus-replacement decision'], approach: "Contact Ellis with your suburb and the affected deck area. Optional safe photos and existing repair records can be emailed to brian@elliservices.com.au. We check boards, supports and connections and compare the repair options in a written quote; do not enter an unsafe space for photos.", boundary: "We assess the deck on site and distinguish surface finishing from support repairs. New construction, an extension or a changed layout is defined as its own agreed scope with required qualified and ACT approval checks. Our work plan confirms safe underside access and retained timber before board replacement; unstable areas should not be used until assessed.", related: ['rotten-timber-repairs','timber-fence-repairs','timber-gate-repairs'] },
  { slug: 'timber-fence-repairs', title: 'Timber Fence Repairs', group: 'Outdoor timber', intro: 'Repairs to timber paling and picket fences, including damaged boards, rails and posts.', symptoms: ['Loose or missing palings', 'A leaning section of fence', 'A post or rail showing damage'], approach: "Contact Ellis with the fence issue and your Canberra suburb. Optional safe photos can be emailed to brian@elliservices.com.au. We measure the affected length, assess posts and rails and confirm repair and replacement options, access and the written quote.", boundary: "We check posts, rails and the function of the fence before specifying repair. Boundary position and owner agreement are confirmed before shared-boundary work, and cost-sharing arrangements remain distinct from our physical work quote. Changes to height, line or style and any retaining or safety-barrier function receive the relevant project checks; qualified non-timber or powered-gate work is coordinated in the scope.", related: ['timber-gate-repairs','deck-repairs','rotten-timber-repairs'] },
  { slug: 'timber-gate-repairs', title: 'Timber Gate Repairs', group: 'Outdoor timber', intro: 'For sagging garden and side gates, timber frames, posts, hinges and latches.', symptoms: ['A gate that drags or will not close', 'A hinge pulling away from timber', 'A soft or moving gate post'], approach: "Contact Ellis about the gate movement, sagging or latch issue and your Canberra suburb. Photos are optional and can be emailed to brian@elliservices.com.au. We assess the gate and supports together and confirm adjustment, retained components and replacement work in your quote.", boundary: "We assess posts, fixings, hinges, latch and clearance as a complete assembly. A motorised drive or wiring is handled through the required qualified service arrangements, with timber and powered work identified separately in the scope. Shared-boundary consent and supporting masonry or structural fixings are checked before work; the gate repair plan defines safe operation and access.", related: ['timber-fence-repairs','door-and-frame-repairs','rotten-timber-repairs'] },
  { slug: 'skirting-and-architraves', title: 'Skirting Boards & Architraves', group: 'Interior finishing', intro: 'Interior finish carpentry for skirting boards, architraves and timber trim around doors and windows.', symptoms: ['Skirting removed for new flooring', 'Damaged or missing architrave sections', 'A trim profile that needs matching'], approach: "Contact Ellis with the rooms or openings needing trim and your Canberra suburb. Optional profile photos, plans or approximate lengths can be emailed to brian@elliservices.com.au. We measure on site and confirm the flooring junction, selected profile, installation and finish in your quote.", boundary: "We confirm the profile, material, supply, installation and finish before work is agreed. Our assessment checks adjoining door frames, flooring and moisture damage so the quoted trim work follows the required repair sequence. Wet-area junctions receive applicable qualified checks, and painting or floor work is included only where stated in the approved quote.", related: ['door-and-frame-repairs','small-carpentry-jobs','cabinet-door-and-drawer-repairs'] },
  { slug: 'cabinet-door-and-drawer-repairs', title: 'Cabinet Door & Drawer Repairs', group: 'Interior finishing', intro: "Ellis Services Group repairs dropped cupboard doors, loose hinges, damaged fixing points, drawer runners and kickboards in Canberra, with the compatible repair confirmed on site.", metaDescription: 'Cabinet door repair in Canberra for dropped doors, loose hinges and damaged fixing points. Get a clear scope for cupboard and drawer repairs.', symptoms: ['A cabinet door that drops, rubs or will not close', 'A loose hinge or damaged fixing point in the cabinet panel', 'A drawer runner that sticks or fails, or a loose kickboard'], approach: "Contact Ellis about the affected cupboard door, drawer or wardrobe fitting and your suburb. Optional photos of the fitting can be emailed to brian@elliservices.com.au. We inspect the hardware and fixing points, identify compatible parts and confirm the repair scope and quote.", boundary: "We check hinge and runner compatibility, part availability and sound fixing material before agreeing repair. Active water entry is addressed through confirmed qualified service arrangements before replacement panels are fitted. The work plan identifies supporting substrates for heavy units and distinguishes a local fitting repair from new cabinet manufacture, with materials and finish approved before ordering.", related: ['small-carpentry-jobs','skirting-and-architraves','door-and-frame-repairs'] },
  { slug: 'interior-carpentry', title: 'Interior & Renovation Carpentry', group: 'Interior carpentry', intro: 'Carpentry finishing and fitting work inside Canberra homes, including shelves, panelling and renovation details.', symptoms: ['Trims left unfinished after a renovation', 'Shelves needed in an awkward alcove', 'Interior timber details that need measuring and fitting'], approach: "Contact Ellis with the room, intended use and your Canberra suburb. Optional plans, sketches or photos can be emailed to brian@elliservices.com.au. We measure and check the fixing areas on site, then confirm the installation layout, materials, finish and quote.", boundary: "Our measured proposal defines on-site fitting and finishing, materials, fixings and the intended use. Structural or wet-area work and concealed electrical or plumbing services are checked through the relevant qualified arrangements before installation. We assess wall substrates for heavy fixtures and confirm manufacture, fit-out and finishing as stated inclusions, not unapproved changes to a structural wall.", related: ['skirting-and-architraves','custom-joinery','cabinet-door-and-drawer-repairs'] },
  { slug: 'timber-weatherboard-repairs', title: 'Timber Weatherboard Repairs', group: 'Exterior carpentry', intro: 'Assessment and replacement of damaged timber weatherboards and external cladding sections.', symptoms: ['A cracked or split weatherboard', 'Localised weathering at board ends', 'Moisture damage beneath an exterior coating'], approach: "Contact Ellis with the affected wall and your suburb. Optional safe photos can be emailed to brian@elliservices.com.au. We check the board profile and lap, damaged length, backing and moisture source and confirm the replacement timber, access and finish in your quote.", boundary: "We identify the cladding material and check the water path behind the cladding before defining replacement. Our team arranges qualified hazardous-material, envelope and structural checks required for the wall. Agreed access establishes the affected backing and adjoining timber; any additional finding is recorded and the repair, profile and finish are confirmed with you before extra work.", related: ['rotten-timber-repairs','fascia-and-eaves-repairs','timber-window-repairs'] },
  { slug: 'timber-stair-and-handrail-repairs', title: 'Timber Stair & Handrail Repairs', group: 'Timber repair', intro: 'Timber stair treads, steps, handrails and balustrade components assessed for an appropriate repair scope.', symptoms: ['A loose timber tread', 'A damaged handrail section', 'Weathered external timber steps'], approach: "Contact Ellis to arrange a safe stair or handrail assessment in your Canberra suburb. Optional photos taken from a safe position can be emailed to brian@elliservices.com.au; do not test the structure with weight. We check supports, fixings and the repair requirements and confirm your quote.", boundary: "Tread support and handrail anchorage are safety-critical components. Avoid relying on a moving rail, tread or incomplete guard until assessed. Our team confirms the qualified structural, ACT practitioner and approval checks for the repair and addresses associated wall or water damage in the work plan. Secure fixing is specified from assessed supporting material, not a cosmetic screw-only assumption.", related: ['rotten-timber-repairs','interior-carpentry','deck-repairs'] },
  { slug: 'pergola-timber-repairs', title: 'Pergola & Verandah Timber Repairs', group: 'Outdoor timber', intro: 'Repairs to existing pergola, verandah and privacy-screen timber, starting with the damaged component.', symptoms: ['A soft pergola post base', 'Weathered verandah timber', 'A loose privacy-screen component'], approach: "Contact Ellis about the affected pergola or verandah and your Canberra suburb. Safe ground-level photos and existing drawings are optional and can be emailed to brian@elliservices.com.au. We inspect the post, beam and connections and confirm safe support, repair sequence and quote.", boundary: "Our team assesses supports, attached roofing and connections before disturbance and confirms the structural and ACT approval requirements for the proposed work. A new roof or changed footprint receives approval checks rather than being treated as a minor timber patch. Roofing, drainage, electrical fittings and footings are coordinated through the required qualified arrangements, with safe support and access stated in the quote.", related: ['rotten-timber-repairs','deck-repairs','timber-weatherboard-repairs'] },
  { slug: 'custom-joinery', title: 'Custom Joinery & Built-in Storage', group: 'Interior carpentry', intro: "Made-to-fit shelves, built-in storage and cabinetry for Canberra homes, with measured design, manufacture and installation arrangements confirmed in your quote.", symptoms: ['Storage needed under stairs', 'An alcove that needs measured shelving', 'Cabinet doors that need a matched replacement'], approach: "Contact Ellis with the space, storage use and your Canberra suburb. Optional sketches, preferred layouts or photos can be emailed to brian@elliservices.com.au. We measure at several points on site and confirm the design, materials, manufacture and installation arrangements and quote.", boundary: "We confirm the design, manufacture and fitting arrangements, material, edge treatment and finish in the measured proposal. Installation near stairs, structural walls and concealed services receives the required qualified checks before fixing. We review available products and samples with you, define the selected match and include electrical, plumbing or supporting work only within an expressly agreed scope.", related: ['interior-carpentry','cabinet-door-and-drawer-repairs','skirting-and-architraves'] },
{ slug: 'structural-timber-repairs', title: 'Structural Timber Repairs', group: 'Structural carpentry', intro: "Ellis Services Group assesses and repairs damaged timber framing, joists and bearers in Canberra. We confirm the repair method and project requirements before work begins.", symptoms: ['A damaged joist or bearer', 'Timber damage remaining after pest treatment', 'Movement or softness in a load-bearing component'], approach: "Contact Ellis with the affected component and your Canberra suburb to arrange the assessment. Existing engineer, pest or leak reports and safe photos are optional and can be emailed to brian@elliservices.com.au. Do not remove finishes or enter an unsafe space to prepare your enquiry.", boundary: "Our team arranges an on-site assessment to identify the cause and confirm the repair plan and quote. We establish the relevant qualified structural, engineering and ACT approval checks before work is scheduled. Required leak and pest service arrangements are coordinated with the timber repair sequence. Avoid using an unsafe affected area; access and any temporary support are defined before disturbance.", related: ['rotten-timber-repairs','timber-stair-and-handrail-repairs','deck-repairs'] },
  { slug: 'deck-building', title: 'New Deck Construction & Extensions', group: 'Outdoor timber', intro: 'New timber decks and extensions are planned around the site, intended use and any required ACT checks.', symptoms: ['An existing deck is beyond practical board repair', 'A new outdoor platform is being planned', 'A deck extension needs scope and approval checks'], approach: "Contact Ellis with the intended deck use and your Canberra suburb. Optional plans, approximate dimensions or safe site photos can be emailed to brian@elliservices.com.au. We measure the site and confirm the footprint, supports, drainage, materials, required project checks and construction quote.", boundary: "A new deck or extension receives a construction scope distinct from repairing an existing deck. We confirm the footprint, support layout, site constraints and required ACT planning, building and engineering checks before work is scheduled. Excavation, drainage, electrical fittings and retaining details are coordinated through the required qualified arrangements, with materials, stairs, railings and access included as agreed.", related: ['deck-repairs','pergola-timber-repairs','timber-fence-repairs'] },
];

export const faqs = [
  { q: 'Do you take on small carpentry jobs in Canberra?', a: 'Yes. Small carpentry jobs are one of our core service areas. Contact Ellis with your task list and suburb; optional photos can be emailed and we confirm the assessment and quote.', owner: 'small-carpentry-jobs', group: 'Booking & quotes' },
  { q: 'Can several small repairs be quoted together?', a: 'Describe each item and provide a photo where possible. We arrange an on-site assessment of the listed tasks and confirm the repair scope and quote.', owner: 'small-carpentry-jobs', group: 'Booking & quotes' },
  { q: 'How is a carpentry repair quote prepared?', a: 'We inspect the affected component and confirm the repair extent, materials, access, removal and finishing in your written quote. Additional findings and changes are agreed with you before extra work proceeds.', owner: 'small-carpentry-jobs', group: 'Booking & quotes' },
  { q: 'Can I send photos before booking?', a: 'Yes. Email optional safe photos to brian@elliservices.com.au. A description alone is also enough to contact Ellis; we assess the cause on site and confirm the repair plan and quote.', owner: 'small-carpentry-jobs', group: 'Booking & quotes' },
  { q: 'Can a timber door be adjusted after new flooring?', a: 'Often the new floor changes the available clearance. The door construction and required gap should be checked before trimming.', owner: 'door-and-frame-repairs', group: 'Doors & windows' },
  { q: 'Should I call a carpenter or locksmith if a door will not latch?', a: 'Contact Ellis Services Group. We inspect the timber door, frame and latch on site, identify the fault and confirm the repair work and qualified service arrangements.', owner: 'door-and-frame-repairs', group: 'Doors & windows' },
  { q: 'Can a rotten timber window sill be repaired locally?', a: 'We inspect the window sill, frame and surrounding timber on site, trace the moisture source and identify the sections requiring repair. Contact Ellis Services Group for your Canberra assessment and repair quote.', owner: 'timber-window-repairs', group: 'Doors & windows' },
  { q: 'Why does repaired timber sometimes rot again?', a: 'Moisture that continues to reach the timber can cause repeat damage. The source should be addressed as part of planning the repair.', owner: 'rotten-timber-repairs', group: 'Exterior timber' },
  { q: 'Can deck boards be replaced without rebuilding the frame?', a: 'We inspect the supporting bearers, joists, posts and fixings on site, then confirm whether board replacement or a support repair is the appropriate scope and provide a quote.', owner: 'deck-repairs', group: 'Exterior timber' },
  { q: 'Should a leaning timber fence be repaired or replaced?', a: 'Ellis checks the posts, rails and affected fence length on site and compares repair and replacement. Your quote identifies retained timber, support work, materials and access.', owner: 'timber-fence-repairs', group: 'Exterior timber' },
  { q: 'What usually causes a timber gate to sag?', a: 'A moving post, loose hinges or a gate frame that has shifted can each contribute. The whole assembly should be checked.', owner: 'timber-gate-repairs', group: 'Exterior timber' },
  { q: 'What is the difference between skirting boards and architraves?', a: 'Skirting boards finish the base of a wall. Architraves trim around doors and windows. Both should be matched to the adjoining profile where possible.', owner: 'skirting-and-architraves', group: 'Interior finishes' },
  { q: 'Can one cupboard door or drawer runner be repaired?', a: 'We inspect the hinge or drawer runner and its fixing points on site, identify the compatible repair parts and confirm the work and quote.', owner: 'cabinet-door-and-drawer-repairs', group: 'Interior finishes' },
];

export const articles = editorialArticles;

export const areas = [
  ['Belconnen',['Belconnen','Kaleen','Florey','Aranda']],
  ['Gungahlin',['Gungahlin','Amaroo','Casey','Ngunnawal']],
  ['Inner North & City',['City','Braddon','Ainslie','Dickson']],
  ['Inner South',['Kingston','Griffith','Red Hill','Narrabundah']],
  ['Woden Valley',['Woden','Curtin','Chifley','Phillip']],
  ['Weston Creek',['Weston','Duffy','Fisher','Holder']],
  ['Tuggeranong',['Tuggeranong','Kambah','Wanniassa','Gowrie']],
  ['Molonglo Valley',['Denman Prospect','Whitlam','Wright']],
  ['East Canberra',['Fyshwick','Pialligo']],
];
