export const business = {
  name: 'Ellis Services Group',
  legalName: 'ELLIS SERVICES GROUP PTY LTD',
  abn: '96 645 821 745',
  acn: '645 821 745',
  entityType: 'Australian private company',
  abnStatus: 'Active since 11 November 2020',
  gstStatus: 'Registered since 11 November 2020',
  phone: '0405 878 406',
  phoneHref: 'tel:+61405878406',
  email: 'brian@elliservices.com.au',
  address: '121 Marcus Clarke St, Canberra, ACT 2600',
  map: 'https://maps.app.goo.gl/cvWgzfMPhPrDPZnE7',
  register: 'https://abr.business.gov.au/ABN/View?id=645821745',
  googleReviews: 'https://share.google/9J93sm3qIx44KCDtj',
  actRegister: 'https://www.accesscanberra.act.gov.au/business-and-work/public-registers',
};

export const services = [
  { slug: 'small-carpentry-jobs', title: 'Small Carpentry Jobs', group: 'General carpentry', intro: "Ellis Services Group repairs smaller timber items in Canberra and assesses several tasks together for a clear, itemised scope and quote.", symptoms: ['Loose or damaged timber fittings', 'A list of small repairs before a sale or tenancy change', 'Interior and exterior timber items that need attention'], approach: "Contact Ellis with your Canberra suburb and a short list of the tasks. Photos and measurements are optional: email safe photos to brian@elliservices.com.au if you have them. We assess each item on site and confirm the grouped repair scope, access and quote.", boundary: "We confirm the work included, visit arrangements and any minimum charge before booking. Our assessment identifies supporting timber damage and any qualified plumbing, electrical, glazing or structural work associated with the repair. The quote states hardware, painting and disposal inclusions; additional work is assessed and agreed with you before it proceeds.", related: ['door-and-frame-repairs','skirting-and-architraves','cabinet-door-and-drawer-repairs'] },
  { slug: 'door-and-frame-repairs', title: 'Timber Door & Frame Repairs', group: 'Doors and windows', intro: 'For timber doors that stick, scrape, will not latch, or have damaged frames, jambs and thresholds.', symptoms: ['A door rubbing after new flooring', 'A latch that misses the strike plate', 'Split timber around a hinge or a soft door jamb'], approach: "Tell Ellis which door sticks, scrapes or will not latch and your Canberra suburb. Optional safe photos can be emailed to brian@elliservices.com.au. We check the door, frame, hinges and latch on site and confirm the repair and quote.", boundary: "We check the full opening before confirming adjustment or repair. Our team confirms qualified hardware, glazing and compliance checks for lock mechanisms, powered access and fire-rated assemblies where relevant. Movement in the surrounding supports is assessed as part of defining the cause-based repair; the agreed scope identifies timber, hardware, finishing and access.", related: ['rotten-timber-repairs','skirting-and-architraves','timber-window-repairs'] },
  { slug: 'timber-window-repairs', title: 'Timber Window Repairs', group: 'Doors and windows', intro: 'Repairs to timber window frames, sills and weathered sections, with attention to the existing profile.', symptoms: ['Soft or damaged timber at a sill', 'Weathered frame sections', 'A frame that needs assessment before replacement'], approach: "Contact Ellis about the affected window and your Canberra suburb. Optional photos of the window and sill can be emailed to brian@elliservices.com.au. We inspect the timber, profile, glazing and water path and confirm the retained sections, repair and finish in your quote.", boundary: "We assess timber, glazing retention and water entry together. Required glazing, sash hardware and qualified building checks are coordinated in the work plan before timber is replaced and finished. We agree access to concealed joints where needed, record further findings and confirm additional work with you rather than treating a photograph as proof of sound concealed timber.", related: ['rotten-timber-repairs','fascia-and-eaves-repairs','door-and-frame-repairs'] },
  { slug: 'rotten-timber-repairs', title: 'Rotten Timber Repairs', group: 'Timber repair', intro: 'On-site inspection and repairs for damaged timber, including identifying the moisture source and the sections requiring replacement.', symptoms: ['Soft timber at an exterior opening', 'Repeated water damage', 'A damaged section requiring on-site inspection'], approach: "Contact Ellis with the timber location, damage you have noticed and your Canberra suburb. Reports and safe photos are optional and can be emailed to brian@elliservices.com.au. We assess the moisture source and sound retained timber before confirming your repair plan and quote.", boundary: "We identify the cause and confirm the repair plan and quote after on-site assessment. Our team arranges qualified leak, pest and structural checks required for the affected component. Agreed inspection access establishes the damage boundary at sound timber; additional concealed findings are documented and any change to the approved work and price is confirmed with you.", related: ['timber-window-repairs','door-and-frame-repairs','fascia-and-eaves-repairs'] },
  { slug: 'fascia-and-eaves-repairs', title: 'Fascia & Eaves Repairs', group: 'Exterior carpentry', intro: "Ellis Services Group assesses and repairs timber fascia boards, bargeboards and eaves details in Canberra, identifying materials and water sources before confirming the repair and quote.", metaDescription: 'Fascia and eaves repairs in Canberra for soft timber, split bargeboards and damaged lining. Identify the material and water source before work is scoped.', symptoms: ['Soft or peeling timber fascia near a gutter', 'A split or weathered bargeboard at a gable', 'A damaged eaves lining or soffit edge that needs material checks'], approach: "Contact Ellis about the affected fascia, bargeboard or eaves and your suburb. Optional photos taken safely from ground level can be emailed to brian@elliservices.com.au. We identify the material, inspect the water path and confirm safe access, repair arrangements and quote.", boundary: "Our team checks the moisture source and confirms the roofing or guttering trade arrangements required for the timber repair. We identify unknown lining materials and arrange qualified hazardous-material or electrical checks before disturbance. The quote sets out roof-edge access equipment, retained fixings, timber and finishing work, with any further concealed damage recorded and agreed before extra work.", related: ['rotten-timber-repairs','timber-weatherboard-repairs','timber-window-repairs'] },
  { slug: 'deck-repairs', title: 'Deck Repairs & Board Replacement', group: 'Outdoor timber', intro: 'Repair and board replacement for existing timber decks, with boards and framing considered separately.', symptoms: ['Individual deck boards that have deteriorated', 'Loose fixings or uneven boards', 'An older deck needing a repair-versus-replacement decision'], approach: "Contact Ellis with your suburb and the affected deck area. Optional safe photos and existing repair records can be emailed to brian@elliservices.com.au. We check boards, supports and connections and compare the repair options in a written quote; do not enter an unsafe space for photos.", boundary: "We assess the deck on site and distinguish surface finishing from support repairs. New construction, an extension or a changed layout is defined as its own agreed scope with required qualified and ACT approval checks. Our work plan confirms safe underside access and retained timber before board replacement; unstable areas should not be used until assessed.", related: ['rotten-timber-repairs','timber-fence-repairs','timber-gate-repairs'] },
  { slug: 'timber-fence-repairs', title: 'Timber Fence Repairs', group: 'Outdoor timber', intro: 'Repairs to timber paling and picket fences, including damaged boards, rails and posts.', symptoms: ['Loose or missing palings', 'A leaning section of fence', 'A post or rail showing damage'], approach: "Contact Ellis with the fence issue and your Canberra suburb. Optional safe photos can be emailed to brian@elliservices.com.au. We measure the affected length, assess posts and rails and confirm repair and replacement options, access and the written quote.", boundary: "We check posts, rails and the function of the fence before specifying repair. Boundary position and owner agreement are confirmed before shared-boundary work, and cost-sharing arrangements remain distinct from our physical work quote. Changes to height, line or style and any retaining or safety-barrier function receive the relevant project checks; qualified non-timber or powered-gate work is coordinated in the scope.", related: ['timber-gate-repairs','deck-repairs','rotten-timber-repairs'] },
  { slug: 'timber-gate-repairs', title: 'Timber Gate Repairs', group: 'Outdoor timber', intro: 'For sagging garden and side gates, timber frames, posts, hinges and latches.', symptoms: ['A gate that drags or will not close', 'A hinge pulling away from timber', 'A soft or moving gate post'], approach: "Contact Ellis about the gate movement, sagging or latch issue and your Canberra suburb. Photos are optional and can be emailed to brian@elliservices.com.au. We assess the gate and supports together and confirm adjustment, retained components and replacement work in your quote.", boundary: "We assess posts, fixings, hinges, latch and clearance as a complete assembly. A motorised drive or wiring is handled through the required qualified service arrangements, with timber and powered work identified separately in the scope. Shared-boundary consent and supporting masonry or structural fixings are checked before work; the gate repair plan defines safe operation and access.", related: ['timber-fence-repairs','door-and-frame-repairs','rotten-timber-repairs'] },
  { slug: 'skirting-and-architraves', title: 'Skirting Boards & Architraves', group: 'Interior finishing', intro: 'Interior finish carpentry for skirting boards, architraves and timber trim around doors and windows.', symptoms: ['Skirting removed for new flooring', 'Damaged or missing architrave sections', 'A trim profile that needs matching'], approach: "Contact Ellis with the rooms or openings needing trim and your Canberra suburb. Optional profile photos, plans or approximate lengths can be emailed to brian@elliservices.com.au. We measure on site and confirm the flooring junction, selected profile, installation and finish in your quote.", boundary: "We confirm the profile, material, supply, installation and finish before work is agreed. Our assessment checks adjoining door frames, flooring and moisture damage so the quoted trim work follows the required repair sequence. Wet-area junctions receive applicable qualified checks, and painting or floor work is included only where stated in the approved quote.", related: ['door-and-frame-repairs','small-carpentry-jobs','cabinet-door-and-drawer-repairs'] },
  { slug: 'cabinet-door-and-drawer-repairs', title: 'Cabinet Door & Drawer Repairs', group: 'Interior finishing', intro: "Ellis Services Group repairs dropped cupboard doors, loose hinges, damaged fixing points, drawer runners and kickboards in Canberra, with the compatible repair confirmed on site.", metaDescription: 'Cabinet door repair in Canberra for dropped doors, loose hinges and damaged fixing points. Get a clear scope for cupboard and drawer repairs.', symptoms: ['A cabinet door that drops, rubs or will not close', 'A loose hinge or damaged fixing point in the cabinet panel', 'A drawer runner that sticks or fails, or a loose kickboard'], approach: "Contact Ellis about the affected cupboard door, drawer or wardrobe fitting and your suburb. Optional photos of the fitting can be emailed to brian@elliservices.com.au. We inspect the hardware and fixing points, identify compatible parts and confirm the repair scope and quote.", boundary: "We check hinge and runner compatibility, part availability and sound fixing material before agreeing repair. Active water entry is addressed through confirmed qualified service arrangements before replacement panels are fitted. The work plan identifies supporting substrates for heavy units and distinguishes a local fitting repair from new cabinet manufacture, with materials and finish approved before ordering.", related: ['small-carpentry-jobs','skirting-and-architraves','door-and-frame-repairs'] },
  { slug: 'interior-carpentry', title: 'Interior & Renovation Carpentry', group: 'Interior carpentry', intro: 'Carpentry finishing and fitting work inside Canberra homes, including shelves, panelling and renovation details.', symptoms: ['Trims left unfinished after a renovation', 'Shelves needed in an awkward alcove', 'Interior timber details that need measuring and fitting'], approach: "Contact Ellis with the room, intended use and your Canberra suburb. Optional plans, sketches or photos can be emailed to brian@elliservices.com.au. We measure and check the fixing areas on site, then confirm the installation layout, materials, finish and quote.", boundary: "Our measured proposal defines on-site fitting and finishing, materials, fixings and the intended use. Structural or wet-area work and concealed electrical or plumbing services are checked through the relevant qualified arrangements before installation. We assess wall substrates for heavy fixtures and confirm manufacture, fit-out and finishing as stated inclusions, not unapproved changes to a structural wall.", related: ['skirting-and-architraves','custom-joinery','cabinet-door-and-drawer-repairs'] },
  { slug: 'timber-weatherboard-repairs', title: 'Timber Weatherboard Repairs', group: 'Exterior carpentry', intro: 'Assessment and replacement of damaged timber weatherboards and external cladding sections.', symptoms: ['A cracked or split weatherboard', 'Localised weathering at board ends', 'Moisture damage beneath an exterior coating'], approach: "Contact Ellis with the affected wall and your suburb. Optional safe photos can be emailed to brian@elliservices.com.au. We check the board profile and lap, damaged length, backing and moisture source and confirm the replacement timber, access and finish in your quote.", boundary: "We identify the cladding material and check the water path behind the cladding before defining replacement. Our team arranges qualified hazardous-material, envelope and structural checks required for the wall. Agreed access establishes the affected backing and adjoining timber; any additional finding is recorded and the repair, profile and finish are confirmed with you before extra work.", related: ['rotten-timber-repairs','fascia-and-eaves-repairs','timber-window-repairs'] },
  { slug: 'timber-stair-and-handrail-repairs', title: 'Timber Stair & Handrail Repairs', group: 'Timber repair', intro: 'Timber stair treads, steps, handrails and balustrade components assessed for an appropriate repair scope.', symptoms: ['A loose timber tread', 'A damaged handrail section', 'Weathered external timber steps'], approach: "Contact Ellis to arrange a safe stair or handrail assessment in your Canberra suburb. Optional photos taken from a safe position can be emailed to brian@elliservices.com.au; do not test the structure with weight. We check supports, fixings and the repair requirements and confirm your quote.", boundary: "Tread support and handrail anchorage are safety-critical components. Avoid relying on a moving rail, tread or incomplete guard until assessed. Our team confirms the qualified structural, ACT practitioner and approval checks for the repair and addresses associated wall or water damage in the work plan. Secure fixing is specified from assessed supporting material, not a cosmetic screw-only assumption.", related: ['rotten-timber-repairs','interior-carpentry','deck-repairs'] },
  { slug: 'pergola-timber-repairs', title: 'Pergola & Verandah Timber Repairs', group: 'Outdoor timber', intro: 'Repairs to existing pergola, verandah and privacy-screen timber, starting with the damaged component.', symptoms: ['A soft pergola post base', 'Weathered verandah timber', 'A loose privacy-screen component'], approach: "Contact Ellis about the affected pergola or verandah and your Canberra suburb. Safe ground-level photos and existing drawings are optional and can be emailed to brian@elliservices.com.au. We inspect the post, beam and connections and confirm safe support, repair sequence and quote.", boundary: "Our team assesses supports, attached roofing and connections before disturbance and confirms the structural and ACT approval requirements for the proposed work. A new roof or changed footprint receives approval checks rather than being treated as a minor timber patch. Roofing, drainage, electrical fittings and footings are coordinated through the required qualified arrangements, with safe support and access stated in the quote.", related: ['rotten-timber-repairs','deck-repairs','timber-weatherboard-repairs'] },
  { slug: 'custom-joinery', title: 'Custom Joinery & Built-in Storage', group: 'Interior carpentry', intro: "Made-to-fit shelves, built-in storage and cabinetry for Canberra homes, with measured design, manufacture and installation arrangements confirmed in your quote.", symptoms: ['Storage needed under stairs', 'An alcove that needs measured shelving', 'Cabinet doors that need a matched replacement'], approach: "Contact Ellis with the space, storage use and your Canberra suburb. Optional sketches, preferred layouts or photos can be emailed to brian@elliservices.com.au. We measure at several points on site and confirm the design, materials, manufacture and installation arrangements and quote.", boundary: "We confirm the design, manufacture and fitting arrangements, material, edge treatment and finish in the measured proposal. Installation near stairs, structural walls and concealed services receives the required qualified checks before fixing. We review available products and samples with you, define the selected match and include electrical, plumbing or supporting work only within an expressly agreed scope.", related: ['interior-carpentry','cabinet-door-and-drawer-repairs','skirting-and-architraves'] },
  { slug: 'structural-timber-repairs', title: 'Structural Timber Repairs', group: 'Specialist assessment', intro: "Ellis Services Group arranges qualified assessment and repair planning for damaged timber framing, joists and bearers in Canberra, with structural requirements confirmed before work.", symptoms: ['A damaged joist or bearer', 'Timber damage remaining after pest treatment', 'Movement or softness in a load-bearing component'], approach: "Contact Ellis with the affected component and your Canberra suburb to arrange the assessment. Existing engineer, pest or leak reports and safe photos are optional and can be emailed to brian@elliservices.com.au. Do not remove finishes or enter an unsafe space to prepare your enquiry.", boundary: "Our team arranges an on-site assessment to identify the cause and confirm the repair plan and quote. We establish the relevant qualified structural, engineering and ACT approval checks before work is scheduled. Required leak and pest service arrangements are coordinated with the timber repair sequence. Avoid using an unsafe affected area; access and any temporary support are defined before disturbance.", related: ['rotten-timber-repairs','timber-stair-and-handrail-repairs','deck-repairs'] },
  { slug: 'deck-building', title: 'New Deck Construction & Extensions', group: 'Outdoor timber', intro: 'New timber decks and extensions are planned around the site, intended use and any required ACT checks.', symptoms: ['An existing deck is beyond practical board repair', 'A new outdoor platform is being planned', 'A deck extension needs scope and approval checks'], approach: "Contact Ellis with the intended deck use and your Canberra suburb. Optional plans, approximate dimensions or safe site photos can be emailed to brian@elliservices.com.au. We measure the site and confirm the footprint, supports, drainage, materials, required project checks and construction quote.", boundary: "A new deck or extension receives a construction scope distinct from repairing an existing deck. We confirm the footprint, support layout, site constraints and required ACT planning, building and engineering checks before work is scheduled. Excavation, drainage, electrical fittings and retaining details are coordinated through the required qualified arrangements, with materials, stairs, railings and access included as agreed.", related: ['deck-repairs','pergola-timber-repairs','timber-fence-repairs'] },
];

export const faqs = [
  { q: 'Do you take on small carpentry jobs in Canberra?', a: 'Yes. Small carpentry jobs are one of our core service areas. Contact Ellis with your task list and suburb; optional photos can be emailed and we confirm the assessment and quote.', owner: 'small-carpentry-jobs', group: 'Booking & quotes' },
  { q: 'Can several small repairs be quoted together?', a: 'Describe each item and provide a photo where possible. We arrange an on-site assessment of the listed tasks and confirm the repair scope and quote.', owner: 'small-carpentry-jobs', group: 'Booking & quotes' },
  { q: 'How is a carpentry repair quote prepared?', a: 'We inspect the affected component and confirm the repair extent, materials, access, removal and finishing in your written quote. Additional findings and changes are agreed with you before extra work proceeds.', owner: 'small-carpentry-jobs', group: 'Booking & quotes' },
  { q: 'Can I send photos before booking?', a: 'Yes. Email optional safe photos to brian@elliservices.com.au. A description alone is also enough to contact Ellis; we assess the cause on site and confirm the repair plan and quote.', owner: 'small-carpentry-jobs', group: 'Booking & quotes' },
  { q: 'Can a timber door be adjusted after new flooring?', a: 'Often the new floor changes the available clearance. The door construction and required gap should be checked before trimming.', owner: 'door-and-frame-repairs', group: 'Doors & windows' },
  { q: 'Should I call a carpenter or locksmith if a door will not latch?', a: 'Contact Ellis Services Group. We inspect the timber door, frame and latch on site, identify the fault and confirm the repair work and qualified service arrangements.', owner: 'door-and-frame-repairs', group: 'Doors & windows' },
  { q: 'Can a rotten timber window sill be repaired locally?', a: 'We inspect the window sill, frame and surrounding timber on site, trace the moisture source and identify the sections requiring repair. Contact Ellis Services Group for your Canberra assessment and repair quote.', owner: 'timber-window-repairs', group: 'Doors & windows' },
  { q: 'Why does repaired timber sometimes rot again?', a: 'Moisture that continues to reach the timber can cause repeat damage. The source should be addressed as part of planning the repair.', owner: 'rotten-timber-repairs', group: 'Exterior timber' },
  { q: 'Can deck boards be replaced without rebuilding the frame?', a: 'We inspect the supporting bearers, joists, posts and fixings on site, then confirm whether board replacement or a support repair is the appropriate scope and provide a quote.', owner: 'deck-repairs', group: 'Exterior timber' },
  { q: 'Should a leaning timber fence be repaired or replaced?', a: 'Ellis checks the posts, rails and affected fence length on site and compares repair and replacement. Your quote identifies retained timber, support work, materials and access.', owner: 'timber-fence-repairs', group: 'Exterior timber' },
  { q: 'What usually causes a timber gate to sag?', a: 'A moving post, loose hinges or a gate frame that has shifted can each contribute. The whole assembly should be checked.', owner: 'timber-gate-repairs', group: 'Exterior timber' },
  { q: 'What is the difference between skirting boards and architraves?', a: 'Skirting boards finish the base of a wall. Architraves trim around doors and windows. Both should be matched to the adjoining profile where possible.', owner: 'skirting-and-architraves', group: 'Interior finishes' },
  { q: 'Can one cupboard door or drawer runner be repaired?', a: 'We inspect the hinge or drawer runner and its fixing points on site, identify the compatible repair parts and confirm the work and quote.', owner: 'cabinet-door-and-drawer-repairs', group: 'Interior finishes' },
];

export const articles = [
  { slug:'timber-door-sticks-after-rain', title:'Why a timber door sticks after wet weather', category:'Doors & windows', owner:'door-and-frame-repairs', lead:'A sticking door can be a clearance issue, but trimming is not always the first step.', sections:[['What changes after rain?','Timber absorbs and releases moisture. A door, frame or adjoining finish can move enough to affect the closing gap. Hinges and latch alignment can also contribute.'],['What should be checked?','Look for where the door touches the frame, whether the hinges are secure and whether water is reaching exposed edges. A carpenter can assess the door and frame before deciding on adjustment or repair.'],['Coordinate the complete door repair','Ellis checks the door, frame, latch and water entry and confirms the qualified hardware and leak repair arrangements in the work plan before finishing the timber.']] },
  { slug:'deck-boards-or-frame', title:'Deck boards or deck framing: what needs repair?', category:'Deck care', owner:'deck-repairs', lead:'A worn board and a damaged supporting structure call for different scopes of work.', sections:[['Start with the walking surface','Look for splintering, loose fixings and areas that feel uneven. These observations help describe the issue but do not prove the frame is sound.'],['Check below the boards','Bearers, joists, posts and connections support the deck. Their condition should be assessed before board-only replacement is agreed.'],['Plan the quote','Our team inspects the boards and supports on site and confirms the repair plan, materials, removal and finish in your quote.']] },
  { slug:'rotten-window-sill', title:'Can a rotten timber window sill be repaired?', category:'Window repairs', owner:'timber-window-repairs', lead:'Ellis Services Group inspects the sill and surrounding timber on site, identifies the moisture source and confirms the repair plan and quote.', sections:[['Assess the whole edge','We check the affected corner, frame, joint and nearby finish on site to establish the full repair area.'],['Address moisture first','We trace the water path at the sill and surrounding opening before planning replacement timber and finishing.'],['Repair or replace','We inspect the surrounding timber on site, define the damaged area and set out the sections to retain and replace in the repair quote.']] },
  { slug:'fascia-bargeboard-eaves', title:'Fascia, bargeboard and eaves lining explained', category:'Exterior timber', owner:'fascia-and-eaves-repairs', lead:'These parts sit close together but perform different jobs at the roof edge.', sections:[['Fascia and bargeboard','A fascia runs along the lower roof edge, often near a gutter. A bargeboard follows a gable edge. Damage should be described by the actual component.'],['Eaves lining','The underside lining may use different materials. Older or unknown material should be identified before disturbance.'],['Why cause matters','Overflowing gutters or other water paths can continue to wet replacement timber. Our team checks the water path on site and confirms the roofing, gutter and timber repair arrangements in the work plan.']] },
  { slug:'leaning-paling-fence', title:'What to check when a paling fence leans', category:'Fences & gates', owner:'timber-fence-repairs', lead:'Ellis Services Group checks the posts, rails and fixings on site, identifies the cause of the lean and confirms the fence repair plan and quote.', sections:[['Identify the affected length','Photograph the whole section and both sides where accessible. Note whether the lean is localised or follows a long run.'],['Check posts and rails','A loose paling is a different repair from a failing post at ground level. The support condition determines the sensible scope.'],['Discuss boundaries','Confirm the relevant property boundary and any shared arrangements separately from the physical repair quote.']] },
  { slug:'skirting-after-new-flooring', title:'Replacing skirting boards after new flooring', category:'Interior finishes', owner:'skirting-and-architraves', lead:'New flooring changes the junction between wall and floor, so matching the skirting profile matters.', sections:[['Record the existing profile','A clear photo, height and approximate length help identify whether a close match is available.'],['Plan the finish','Ellis confirms removal, supply, installation, caulking and painting inclusions in the written trim quote.'],['Check nearby doors','A new floor can also reduce door clearance. That issue belongs in a separate door assessment if required.']] },
  { slug:'why-timber-gates-sag', title:'Why timber side gates sag or stop latching', category:'Fences & gates', owner:'timber-gate-repairs', lead:'A dragging gate can point to a hinge, frame or post issue rather than the gate leaf alone.', sections:[['Check the whole assembly','Look at the gate frame, support post, hinges, latch and ground clearance. A moving post can undo a simple hinge adjustment.'],['After wet weather','Timber movement and exposed edges can affect alignment. Trimming an edge without checking the cause may not resolve the issue.'],['Describe the repair','Photograph the closed gate, hinge fixings and post base so the first discussion covers the complete scope.']] },
  { slug:'why-timber-rot-returns', title:'Why rotten timber can return after a repair', category:'Timber care', owner:'rotten-timber-repairs', lead:'A local timber patch is only part of the answer if the source of moisture remains.', sections:[['Find the water path','Look for repeated wetting, failed coatings, damaged joints or leaks around the affected component.'],['Check beyond the surface','Paint may hide soft timber. The repair boundary should reach sound material and preserve the function of the component.'],['Coordinate the water-source repair','Our team confirms the qualified gutter, roof or plumbing repair arrangements and addresses the water source before the replacement timber is finished.']] },
  { slug:'cabinet-hinges-and-drawer-runners', title:'When one cupboard door or drawer stops working', category:'Cabinet repairs', owner:'cabinet-door-and-drawer-repairs', lead:'A single failed fitting does not always mean a whole kitchen or wardrobe needs replacing.', sections:[['Identify the failed part','Check the hinge, runner, fixing points and surrounding panel. A replacement fitting must suit the existing cabinet.'],['Measure before sourcing','Photos and approximate dimensions help determine whether compatible hardware is available.'],['Look for water damage','If a kickboard or panel has swollen after a leak, the source should be dealt with before fitting a replacement.']] },
  { slug:'timber-weatherboard-damage', title:'When a few timber weatherboards are damaged', category:'Exterior timber', owner:'timber-weatherboard-repairs', lead:'A cracked board may be locally replaceable, but profile matching and moisture detail matter.', sections:[['Check the affected run','Photograph the cracked ends, joints and surrounding boards. The visible damage may not mark the full repair length.'],['Match the profile','Board dimensions and profile affect how a replacement meets neighbouring cladding.'],['Plan the finish','Confirm whether priming, painting and any broader wall-envelope work are included in the scope.']] },
  { slug:'loose-timber-stairs', title:'What to do when a timber stair tread feels loose', category:'Stairs & handrails', owner:'timber-stair-and-handrail-repairs', lead:'A moving tread or handrail deserves assessment of its support before a cosmetic repair.', sections:[['Start with safety','Avoid relying on a loose step or handrail. Describe where it moves and whether the surrounding structure is affected.'],['Check the supports','The tread, fixings and supporting members must be considered together.'],['Confirm the right practitioner','Ellis confirms the required qualified structural, ACT practitioner and approval checks before the stair repair is agreed.']] },
  { slug:'pergola-post-rot', title:'A soft pergola post: repair or broader assessment?', category:'Outdoor timber', owner:'pergola-timber-repairs', lead:'A decayed post base can affect the support of the whole pergola or verandah.', sections:[['Do not remove it first','The connected structure and load path should be understood before a support post is disturbed.'],['Look for the cause','Water exposure at ground level, failed coatings and nearby drainage can affect the replacement detail.'],['Check approvals','Our team confirms the required ACT approval checks and qualified practitioner arrangements for the pergola repair or alteration before work.']] },
  {
    slug: 'repair-or-rebuild-a-deck',
    title: 'Repair an existing deck or plan a new one?',
    category: 'Deck planning',
    owner: 'deck-building',
    updated: '2026-10-07',
    metaDescription: 'Ellis compares Canberra deck board repairs, frame repairs and rebuilding after assessment, with a clear quote, approved changes and maintenance handover.',
    lead: 'Ellis Services Group checks the deck boards, supporting timber, connections and persistent moisture before comparing local repairs, frame repairs and rebuilding. The right scope follows the condition we find and the way you want to use the deck.',
    sections: [
      ['Assess the existing deck as a whole', 'We review the walking surface separately from the joists, bearers, posts and connections that support it. A neat-looking board surface does not confirm the condition underneath. Ellis checks the affected components and moisture exposure from planned access, then explains which parts can be retained and which require repair. If the deck is loose, unstable or visibly damaged, stop using the affected area and arrange an assessment. Do not crawl into an unsafe space below it or test it with extra weight.'],
      ['Local board repair', 'A defined board repair retains sound surrounding boards and confirmed supports. Ellis identifies the boards and fixings to replace, checks adjoining edges and describes the finish included. Where the supporting timber also needs work, the scope expands to address that condition before replacement boards are installed.'],
      ['Frame and connection repairs', 'Damage to joists, bearers, posts or connections calls for a support repair plan rather than a fresh board surface alone. We inspect the affected area, assess what can be retained and define the repair sequence, access and components included. Addressing persistent dampness and the relevant water path is part of planning a durable result.'],
      ['Rebuild or change the deck layout', 'When retaining the existing system will not deliver the agreed outcome, Ellis compares rebuilding with repair. The new scope identifies the footprint, height, intended use, materials, access, stairs and any railings involved. Changes to the deck need project-specific ACT approval checks before work is agreed; building approval and planning requirements are separate checks, not a single height rule.'],
      ['From assessment to a written quote', 'Contact Ellis with your Canberra suburb and the affected area. Safe photos and existing repair records are optional and can be emailed to brian@elliservices.com.au. Ellis confirms the assessment and access arrangements, checks the board and support conditions, then sets out the recommended option. Our written quote identifies demolition or removal, retained and replaced components, timber and fixings, finish, waste removal, access arrangements and the agreed project requirements. We confirm planned inspection access and document additional findings; any change to the work, price or scheduling is agreed with you before extra work proceeds.'],
      ['Confirm additional findings before extending the work', 'If opening the agreed area reveals further deterioration, we record the finding and explain its effect on the repair. A written variation confirms the additional components, price basis and scheduling effect before that work proceeds. Keeping the approved scope and changes together avoids treating an initial estimate as permission for unlimited work.'],
      ['Check the repair and plan its maintenance', 'At completion, review the repaired areas against the agreed scope, note any remaining restrictions or follow-up, and retain the handover record. Keep debris and persistent moisture under review and follow the care guidance for the selected timber and finish. A coating maintenance task is distinct from checking a support or connection that shows movement or deterioration.']
    ],
    options: [
      { option: 'Local board repair', assessment: 'Defined board damage with supports checked and suitable for retention.', scope: 'Specified boards, fixings, adjoining details and finish.' },
      { option: 'Frame and connection repairs', assessment: 'Deterioration in a supporting member or connection that can be addressed within a defined repair.', scope: 'Support components, repair sequence, safe access and the moisture source.' },
      { option: 'Rebuild', assessment: 'Extensive connected defects or a changed layout and use requiring a new construction scope.', scope: 'Removal, new deck system, access, materials and applicable ACT project checks.' }
    ],
    faqs: [
      { q: 'Can new boards solve a damaged frame?', a: 'No. Ellis checks the supports and connections before agreeing board replacement. The scope addresses damaged supporting components as well as the walking surface.' },
      { q: 'Can I decide from the proportion of damaged boards?', a: 'A percentage does not establish the condition of the supports or the cause of damage. We assess boards, supporting timber, connections and moisture together before comparing the options.' },
      { q: 'What happens if more damage is found during repairs?', a: 'Ellis documents the finding and explains the additional work. A written variation confirms the revised scope, pricing basis and scheduling effect before the additional work proceeds.' },
      { q: 'Does a low deck automatically avoid approval checks?', a: 'No. We confirm the project details and applicable ACT building and planning requirements. A repair, extension and new deck can involve different checks.' }
    ],
    relatedLinks: [
      { url: '/services/deck-repairs/', label: 'Deck repair and board replacement' },
      { url: '/services/deck-building/', label: 'New deck construction and extensions' },
      { url: '/news/deck-boards-or-frame/', label: 'What differs between deck boards and framing' },
      { url: '/news/why-timber-rot-returns/', label: 'Why timber rot returns' },
      { url: '/contact/', label: 'Ask Ellis about your Canberra deck' }
    ]
  },
  { slug:'carpentry-jobs-before-selling', title:'Planning small carpentry repairs before a home sale', category:'Interior carpentry', owner:'interior-carpentry', lead:'A grouped list of doors, skirting and cupboard repairs can make the quote discussion clearer.', sections:[['Make one list','Identify each item, location and desired finish. Photos of the whole item and the defect are useful.'],['Separate trades','Our team reviews your repair list on site and confirms the carpentry work and associated qualified service arrangements in the quote.'],['Confirm inclusions','Ellis states materials, removal and finishing inclusions in your quote before the work is booked.']] },
];

export const areas = [
  ['Belconnen',['Belconnen','Kaleen','Florey','Aranda']],
  ['Gungahlin',['Gungahlin','Amaroo','Casey','Ngunnawal']],
  ['Inner North & City',['City','Braddon','Ainslie','Dickson']],
  ['Inner South',['Kingston','Griffith','Red Hill','Narrabundah']],
  ['Woden Valley',['Woden','Curtin','Chifley','Phillip']],
  ['Weston Creek',['Weston','Duffy','Fisher','Holder']],
  ['Tuggeranong',['Tuggeranong','Kambah','Wanniassa','Gowrie']],
  ['Molonglo Valley',['Denman Prospect','Whitlam','Wright']],
  ['East Canberra',['Fyshwick','Pialligo']],
];
